name: aluconnect
description: ALU Stride - Do Hard Things.. the easy way.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  google_fonts: ^8.1.0
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.6
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
